spring.application.name=alchemy-furnace-web
server.port=8081

#dubbo
dubbo.application.name=alchemy-furnace-dubbo-provider
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
# 全局指定序列化方式，可选kryo/protostuff/json等，如果使用第三方序列化 则需额外引入依赖包
dubbo.protocol.serialization=hessian2
dubbo.registry.address=zookeeper://127.0.0.1:2181
##扫描包的路径配置错误会导致真实的serviceBean not found
dubbo.scan.base-packages=com.lee.af.service