spring.application.name=alchemy-furnace-se
server.port=8081

#dubbo
dubbo.application.name=alchemy-furnace-dubbo-provider
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
dubbo.registry.address=zookeeper://127.0.0.1:2181
dubbo.scan.base-packages=com.lee.dubbo.provider