spring.application.name=alchemy-furnace-web
server.port=8081

#dubbo
dubbo.application.name=alchemy-furnace-dubbo-provider
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
dubbo.registry.address=zookeeper://127.0.0.1:2181
##扫描包的路径配置错误会导致真实的serviceBean not found
dubbo.scan.base-packages=com.lee.af.service